import fs from 'fs';

let content = fs.readFileSync('src/types.ts', 'utf8');

content = content.replace(/export type Domain = string;/m, `export type Domain = 
  | 'Frontend Development' 
  | 'Backend Development' 
  | 'Fullstack Development' 
  | 'Mobile App Development'
  | 'DevOps & SRE'
  | 'AI & Machine Learning'
  | 'Data Engineering'
  | 'Software Testing & QA'
  | 'UI/UX Design'
  | 'Cybersecurity' 
  | 'Data Science' 
  | 'Cloud Computing' 
  | 'Mechanical Engineering'
  | 'Electrical Engineering'
  | 'Civil Engineering'
  | 'Chemical Engineering'
  | 'Electronics & Communication Engineering'
  | 'Aptitude & Reasoning' 
  | 'HR & Behavioral'
  | 'Personalized'
  | 'Google'
  | 'Amazon'
  | 'Microsoft'
  | 'Meta'
  | 'Apple'
  | 'TCS'
  | 'Infosys'
  | 'Wipro'
  | 'Accenture'
  | 'Zoho'
  | 'HCL'
  | 'Cognizant'
  | 'Tech Mahindra'
  | 'LTIMindtree'
  | 'Mphasis'
  | 'Core Fundamentals (Fresher)'
  | 'Data Structures and Algorithms (DSA)'
  | 'Database Management System (DBMS)'
  | 'Operating Systems (OS)'
  | 'Computer Networks'
  | 'Object-Oriented Programming (OOP)'
  | 'Python Programming'
  | 'Java Programming'
  | 'JavaScript Programming'
  | 'C/C++ Programming'
  | 'System Design'
  | 'Database Management'
  | 'Embedded Systems'
  | 'Game Development'
  | 'Product Management'
  | 'Project Management'
  | 'Business Analysis'
  | 'Blockchain Development'
  | 'Data Analytics'
  | 'Cloud Architecture'
  | 'Sales & Marketing'
  | 'Finance & Accounting'
  | 'C Programming (Quiz)'
  | 'Java Programming (Quiz)'
  | 'Python Programming (Quiz)'
  | 'C++ Programming (Quiz)';`);

fs.writeFileSync('src/types.ts', content);
